---
- name: Setup hiroshi user, install and configure httpd
  hosts: web_server
  tasks:
    - name: Ensure user hiroshi exists
      user:
        name: hiroshi
        state: present
      become: true

- name: Ensure sudo privileges is granted to hiroshi without password
      lineinfile:
        path: /etc/sudoers.d/hiroshi
        line: 'hiroshi ALL=(ALL) NOPASSWD: ALL'
        create: true
        validate: '/usr/sbin/visudo -cf %s'
      becmoe: true
