---
- name: Setup hiroshi user, install and configure httpd
  hosts: node02.example.com
  become: true #すべての操作に権限昇格が必用なため、このplaybookではプレイ規模で権限昇格を指定して問題ない
  tasks:
    - name: Ensure user hiroshi exists
      user:
        name: hiroshi
        state: present

    - name: Ensure sudo privileges is granted to hiroshi without password
      lineinfile:
        path: /etc/sudoers.d/hiroshi
        line: 'hiroshi ALL=(ALL) NOPASSWD: ALL'
        create: true
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure httpd package is installed
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is running and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Ensure document root directory exists and set permissions
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Ensure a simple index.html is in document root
      copy:
        content: |
          <html>
            <head><title>Welcome</title></head>
            <body><h1>Hello from Hiroshi's HTTP Server</h1></body>
          </html>
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify:
        restart httpd

    handlers:
      - name: restart httpd
        service:
          name: httpd
          state: restarted
