---
- name: Update user hiroshi, install httpd and configure it
  hosts: all
  become: yes  # Playレベルでの権限昇格
  tasks:
    - name: Add user hiroshi
      user:
        name: hiroshi
        state: present

    - name: Ensure the user hiroshi is granted sudo privileges without password
      copy:
        dest: /etc/sudoers.d/hiroshi
        content: 'hiroshi ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure httpd package is installed
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure www directory exists in the home directory of hiroshi
      file:
        path: /home/hiroshi/www
        state: directory
        owner: hiroshi
        group: hiroshi
        mode: '0755'

    - name: Ensure the DocumentRoot is set to www directory of hiroshi home
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot'
        line: 'DocumentRoot "/home/hiroshi/www"'
